### PR TITLE
Vec 218 update 1.0

### PR DESCRIPTION
**Pull request by jdogmcsteezy**
Moved preview and dev docker files into .internal folder. If the customer doesn't need them they should not be there. Reverted the docker compose files to pull the locally built image. That's how the readme says to do it so that should be how it is run.

### CODE REVIEW

**Review by dwelch-spike — APPROVED** [review]
LGTM

**Comment by hev** [comment]
Waiting for 1.0 python client to get published then will re-test.

**Comment by davi17g** [comment]
Would be great if the relative paths in the files moved to `.internal` folder could be updated (especially in `Dockerfile-quote-search-preview` so we can easily rebuild it as needed )

**Comment by jdogmcsteezy** [comment]
@davi17g fixed docker file paths

**Review by davi17g — APPROVED** [review]

**Review by hev — APPROVED** [review]
Tested with 1.0 client.

**Pull request merged**
