### PR TITLE
Optimize deployment add istio

### PR DESCRIPTION
**Pull request by davi17g**

### CODE REVIEW

**Review by hev — COMMENTED** [review]
I got the following error trying this branch.

```
Next steps:
  * Deploy an HTTP Gateway: https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/
  * Deploy an HTTPS Gateway: https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/
error: the path "/manifests/istio" does not exist
Error: 1 at line 153
```

**Comment by arrowplum** [comment]
@davi17g I refactored a little bit and tested with and without istio (so we could have it in an optional section). 

Have a look and make sure it makes sense to you

**Review by hev — CHANGES_REQUESTED** [review]
There are still a few issues here.

1. The reference to the helm chart locations are on David's laptop. 
2. The ordering still seems off. Recommend we do 
    * Install ASDN
    * Install AVS
    * Install Prom + Istio (optional)
    * Validate

I have broken this out into a docs PR [here](https://github.com/citrusleaf/aerospike-websites/pull/792).

**Comment by hev** [comment]
Also, I keep running into the clustername being too long.

**Comment by hev** [comment]
A couple more things.

1. manifests/monitoring needs to be consolidated so it can be reached with a https://raw.githubusercontent URL
2. manifests/istio needs to be consolidated so it can be reached with a https://raw.githubusercontent URL

**Comment by hev** [comment]
I am also not sure the Istio step is working, or how to validate. i still get the error I posted above.

**Comment by arrowplum** [comment]
> There are still a few issues here.
> 
>     1. The reference to the helm chart locations are on David's laptop.
> 
>     2. The ordering still seems off. Recommend we do
>        
>        * Install ASDB
>        * Install AVS
>        * Install Prom + Istio (optional)
>        * Validate
> 
> 
> I have broken this out into a docs PR [here](https://github.com/citrusleaf/aerospike-websites/pull/792).

yeah there is a chicken and egg thing going here. We need to merge this, then update the links, then merge the docs

**Pull request merged**
