### PR TITLE
change docker image location

### PR DESCRIPTION
**Pull request by hev**
Streamline the docker-compose file so you can use it without needing to docker-build.

### CODE REVIEW

**Comment by dwelch-spike** [comment]
This is a double edged sword. It means the docker compose will pull tagged images from dockerhub, so if someone has made local changes to the example in the repo and built their own image it won't be picked up. In the past we forced users to build their own images so that the most recent changes would be incorporated and because Our readme files say to build the images.

**Comment by hev** [comment]
@dwelch-spike I do think we want this. I double checked and we don't use it in ./internal and this is very helpful for docs. See this preview link. I am actually having trouble building locally and running with this compose file atm.

**Comment by hev** [comment]
I made a few tweaks here to address the concern by adding another docker-compose file and updating the READMEs. I also decided to include an example png image to get indexed automatically so that the directories are there.

**Review by arrowplum — APPROVED** [review]
Looks fine. I had a go at just using env vars and dowing away with the dev yaml but probably this is simpler and not too crazy overhead.

Next time we update though we should look at combining them since it is just the image tag.

I have a PR for the feature key in the wings.

**Pull request merged**
